// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import (
	entities "github.com/eduardocfalcao/url-shortener/src/api/entities"

	mock "github.com/stretchr/testify/mock"
)

// ShortUrlRepository is an autogenerated mock type for the ShortUrlRepository type
type ShortUrlRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *ShortUrlRepository) Create(_a0 entities.ShortUrl) (int64, error) {
	ret := _m.Called(_a0)

	var r0 int64
	if rf, ok := ret.Get(0).(func(entities.ShortUrl) int64); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entities.ShortUrl) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
