version: '3.1'

services:
  db:
    extends:
      file: ./docker-stacks/dependencies.yml
      service: db
    container_name: urlshortener_postgres
    ports:
      - 15431:5432

  redis:
    extends:
      file: ./docker-stacks/dependencies.yml
      service: redis
    container_name: urlshortener_redis
    ports:
      - 6378:6379

  pometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./docker-stacks/.prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  url-shortener:
    build: .
    container_name: url-shortener
    ports:
      - 8080:8080
    env_file: 
      - docker.env