
up:
	docker-compose up -d

build:
	docker-compose build

down:
	docker-compose down

dependencies-up:
	docker-compose -f ./docker-stacks/dependencies.yml up -d

dependencies-down:
	docker-compose -f ./docker-stacks/dependencies.yml down

dependencies-rm:
	docker-compose -f ./docker-stacks/dependencies.yml rm -v