#global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  #query_log_file: <string>
  external_labels:
    monitor: 'monitor'
# Scrape configs only contain one scrape target
scrape_configs:
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'url-shortener-job'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['url-shortener:8080']